#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

CHPL_MAKE_HOME = ..
include $(CHPL_MAKE_HOME)/make/Makefile.base

all:
	@$(MAKE) "CHPL_MAKE_HOST_TARGET=--host" printplatform
	@echo
	@$(MAKE) "CHPL_MAKE_HOST_TARGET=--target" printplatform
