#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

PARSER_OBJDIR = $(COMPILER_ROOT)/parser/$(OBJ_SUBDIR)

ALL_SRCS += parser/*.h parser/*.cpp

include $(COMPILER_ROOT)/parser/Makefile.share
