#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

LAUNCH_SUBDIR = src/launch/pbs-aprun

LAUNCH_OBJDIR = $(RUNTIME_ROOT)/$(LAUNCH_SUBDIR)/$(LAUNCHER_OBJDIR)

ALL_SRCS += $(CURDIR)/$(LAUNCH_SUBDIR)/*.c

include $(RUNTIME_ROOT)/$(LAUNCH_SUBDIR)/Makefile.share
