#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

REGEXP_SUBDIR = src/qio/regexp/none

ALL_SRCS += $(CURDIR)/$(REGEXP_SUBDIR)/*.c

REGEXP_OBJDIR = $(RUNTIME_ROOT)/$(REGEXP_SUBDIR)/$(RUNTIME_OBJDIR)

include $(RUNTIME_ROOT)/$(REGEXP_SUBDIR)/Makefile.share
