#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

THREADS_SUBDIR = src/threads/$(CHPL_MAKE_THREADS)

THREADS_OBJDIR = $(RUNTIME_ROOT)/$(THREADS_SUBDIR)/$(RUNTIME_OBJDIR)

ALL_SRCS += $(CURDIR)/$(THREADS_SUBDIR)/*.c

include $(RUNTIME_ROOT)/$(THREADS_SUBDIR)/Makefile.share
