#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

LAUNCHER_SRCS = \
        launch-aprun.c \
        aprun-utils.c \

SVN_SRCS = $(LAUNCHER_SRCS)
SRCS = $(SVN_SRCS)

LAUNCHER_OBJS = \
	$(LAUNCHER_SRCS:%.c=$(LAUNCH_OBJDIR)/%.o)
