#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

MEM_SRCS = mem-default.c

SVN_SRCS = $(MEM_SRCS)
SRCS = $(SVN_SRCS)

MEM_COMMON_OBJS = $(MEM_SRCS:%.c=$(MEM_OBJDIR)/%.o)
