#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

BACKEND_OBJDIR = $(COMPILER_ROOT)/backend/$(OBJ_SUBDIR)

ALL_SRCS += backend/*.cpp

include $(COMPILER_ROOT)/backend/Makefile.share
