#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

MEM_SUBDIR = src/mem/tcmalloc

ALL_SRCS += $(CURDIR)/$(MEM_SUBDIR)/*.c $(CURDIR)/$(MEM_SUBDIR)/*.cc

MEM_OBJDIR = $(RUNTIME_ROOT)/$(MEM_SUBDIR)/$(RUNTIME_OBJDIR)

include $(RUNTIME_ROOT)/$(MEM_SUBDIR)/Makefile.share
