#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

OPTIMIZATIONS_OBJDIR = $(COMPILER_ROOT)/optimizations/$(OBJ_SUBDIR)

ALL_SRCS += optimizations/*.cpp

include $(COMPILER_ROOT)/optimizations/Makefile.share
