#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

GEN_CFLAGS += -I$(QTHREAD_INCLUDE_DIR)
GEN_LFLAGS += -L$(QTHREAD_LIB_DIR) -Wl,-rpath=$(QTHREAD_LIB_DIR)

LIBS += -lqthread_chpl -lqthread

ifneq (, $(filter $(CHPL_MAKE_TARGET_PLATFORM),cray-xe cray-xc cray-xk))
LIBS += -lrt
endif
