#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

MPI_INSTALL = $(OPENMPI_INSTALL_DIR)

GEN_LFLAGS += -I$(MPI_INSTALL)/include -pthread -L$(MPI_INSTALL)/lib
LIBS += -lmpi -lopen-rte -lopen-pal -lrt -ldl -Wl,--export-dynamic -lnsl -lutil -lm -ldl
