#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

LIBS += -L$(ARMCI_LIB_DIR) -L$(MPICH1_LIB_DIR) -larmci -lmpich $(ARMCI_PLATFORM_SPECIFIC_LIBS) -lnsl -lrt

# Does sunos need -lsocket?
