#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

# Makefile.linux64_32: contains linux64-specific variables for compiling
# 32-bit code
#

CFLAGS += -m32
LDFLAGS += -m32
