#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

# Makefile.cygwin: contains cygwin-specific variables
#

EXE_SUFFIX=.exe

#
# seemingly necessary to get vnsprintf for the runtime libraries
#
RUNTIME_CFLAGS += -U__STRICT_ANSI__

#
# seemingly necessary to get INT64_MAX and the like
#
GEN_CFLAGS +=  -U__STRICT_ANSI__
