#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

ifeq ($(CHPL_COMM), gasnet)
  GEN_CFLAGS += -I$(GASNET_INSTALL_DIR)/patched_headers
  GEN_LFLAGS += -L/usr/lib64/nptl
endif
