#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

# put XE cross-compilation pathscale-specific settings here

XE_GEN_CFLAGS = -OPT:Olimit=0

include $(CHPL_MAKE_HOME)/make/compiler/Makefile.cray-xe
