#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

PASSES_OBJDIR = $(COMPILER_ROOT)/passes/$(OBJ_SUBDIR)

ALL_SRCS += passes/*.cpp

include $(COMPILER_ROOT)/passes/Makefile.share
