#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

RESOLUTION_SRCS = \
	caches.cpp \
	callDestructors.cpp \
	callInfo.cpp \
	cullOverReferences.cpp \
	generics.cpp \
	functionResolution.cpp \
	lowerIterators.cpp \
	wrappers.cpp

SVN_SRCS = $(RESOLUTION_SRCS)
SRCS = $(SVN_SRCS)

RESOLUTION_OBJS = \
	$(RESOLUTION_SRCS:%.cpp=$(RESOLUTION_OBJDIR)/%.$(OBJ_SUFFIX))
