#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

RESOLUTION_OBJDIR = $(COMPILER_ROOT)/resolution/$(OBJ_SUBDIR)

ALL_SRCS += resolution/*.cpp

include $(COMPILER_ROOT)/resolution/Makefile.share
