#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

MAIN_SRCS = \
	arg.cpp \
	checks.cpp \
	config.cpp \
	driver.cpp \
	log.cpp \
	runpasses.cpp \
	version.cpp

SVN_SRCS = $(MAIN_SRCS)
SRCS = $(SVN_SRCS)

MAIN_OBJS = \
	$(MAIN_SRCS:%.cpp=$(MAIN_OBJDIR)/%.$(OBJ_SUFFIX))
