#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

LAUNCHER_SRCS = \
        launch-tile-monitor.c \

#
# is this the right time to set this variable?  Or is user code
# compile time
#
RUNTIME_CFLAGS += -DLAUNCH_PATH="$(TILERA_ROOT)/bin/"

SVN_SRCS = $(LAUNCHER_SRCS)
SRCS = $(SVN_SRCS)

LAUNCHER_OBJS = \
	$(LAUNCHER_SRCS:%.c=$(LAUNCH_OBJDIR)/%.o)
