#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

THREADS_SRCS = threads-$(CHPL_MAKE_THREADS).c

SVN_SRCS = $(THREADS_SRCS)
SRCS = $(SVN_SRCS)

THREADS_OBJS = $(THREADS_SRCS:%.c=$(THREADS_OBJDIR)/%.o)
